version: 2.1
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test

workflows:
  build-and-package:
    jobs:
      - build-and-test