version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout 
      - run:
          name: Install dependencies
          command: |
            yarn --frozen-lockfile
      - run:
          name: run tests
          command: |
            yarn test
  pack:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            yarn --frozen-lockfile
      - run:
          name: compiles
          command: |
            yarn build

workflows:
  build-and-package:
    jobs:
      - build
      - pack:
        requires:
          - build